/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in scaffolded projects.
// It is checked in here because the app was created manually on a machine without npm.
